export const metadata = {
  title: "Liên hệ - Mindmap Flow",
  description: "Generated by create next app",
};

const Contact = () => {
  return (
    <section className="">
      <div className="max-w-[450px] w-11/12 p-5 mx-auto my-20 space-y-5 shadow-xl">
        <h4 className="text-center text-3xl text-primary font-medium">
          Contact Us
        </h4>
        <form method="post">
          <div className="grid grid-cols-2 gap-5">
            <input
              className="border border-gray-500 px-4 py-2 focus:outline-none focus:border-purple-500"
              placeholder="First Name"
              type="text"
            />
            <input
              className="border border-gray-500 px-4 py-2 focus:outline-none focus:border-purple-500"
              placeholder="Last Name"
              type="text"
            />
            <input
              className="border border-gray-500 px-4 py-2 focus:outline-none focus:border-purple-500 col-span-2"
              placeholder="Email"
              type="email"
            />
            <input
              className="border border-gray-500 px-4 py-2 focus:outline-none focus:border-purple-500 col-span-2"
              placeholder="Phone"
              type="tel"
            />
            <textarea
              cols="10"
              rows="5"
              className="resize-none border border-gray-500 px-4 py-2 focus:outline-none focus:border-purple-500 col-span-2"
              placeholder="Write your message..."
            ></textarea>
          </div>
          {/* <input
            className="focus:outline-none mt-5 bg-purple-500 px-4 py-2 text-white font-bold w-full"
            type="submit"
            value="Send Message"
          /> */}
          <button className="focus:outline-none mt-5 bg-purple-500 px-4 py-2 text-white font-bold w-full">
            Send Message
          </button>
        </form>
      </div>
    </section>
  );
};

export default Contact;
