import Link from "next/link";
import TableMap from "./components/TableMap";

export const metadata = {
  title: "Mindmap của tôi - Mindmap Flow",
  description: "Generated by create next app",
};

const MindmapPage = () => {
  return (
    <div className="container px-4 pt-8 mx-auto">
      <div className="text-start">
        <h1 className="text-3xl md:text-4xl font-medium my-2 text-gray-800 dark:text-gray-100">
          Mindmap của tôi
        </h1>
        <div className="py-4">
          <Link
            className="rounded-lg px-4 py-2 bg-blue-500 text-blue-100 hover:bg-blue-600 duration-300"
            href="/my-mindmap/create"
          >
            Thêm mới
          </Link>
        </div>
      </div>
      <TableMap />
    </div>
  );
};

export default MindmapPage;
